add filter logs to pipeline
splunk/sck-otel pull request #63
Opened 2021-09-07 17:56 UTC by chaitanyaphalak

## Proposed changes

Add filtering of logs capability

2021-09-07 20:37 UTC, rockb1017 approved these changes

2021-09-07 20:39 UTC, rockb1017 requested changes
CI fails. the agent is failing with this email 
```
Error: cannot load configuration: error reading processors configuration for filter/log: 1 error(s) decoding:

* '' has invalid keys: logs
```

2021-09-08 17:21 UTC, chaitanyaphalak commented
thats because the agent running the CI dosent have the latest changes to filter log. 
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4895 has to be merged first

2021-09-13 23:56 UTC, dmitryax commented on charts/sck-otel/templates/_config.tpl
> +          - key: com.splunk.exclude
Is `com.splunk.exclude` attribute set anywhere in the pipeline before? Shouldn't it be `k8s.pod.annotations.splunk.com/exclude` and `k8s.namespace.annotations.splunk.com/exclude` instead?

2021-10-05 23:37 UTC, rockb1017 commented
it has this error from agent. ```* '' has invalid keys: logs
2021/10/05 23:25:47 main.go:95: application run finished with error: cannot load configuration: error reading processors configuration for filter/namespacelogs: 1 error(s) decoding:```

When CI fails, you can check the stdout on "deploy log generator" steps because it runs `kubectl logs` command.

2021-10-06 00:52 UTC, rockb1017 commented
Could you re enable the filter test case ? 
line 90 in the `test/k8s_logging_tests/test_config_logging.py`

2021-10-12 18:08 UTC, rockb1017 approved these changes

2021-10-12 18:10 UTC, merged